services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: pnpm run start:dev reservation
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  mogo:
    image: mongo