name: Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.5
        options: --health-cmd="docker info > /dev/null || exit 1" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -v

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yaml up --build -d
          docker-compose -f docker-compose.yaml ps
          docker-compose -f docker-compose.yaml logs --follow

      - name: Wait for services to start
        run: sleep 30 # Adjust this based on your services' startup time

      - name: Run tests on your_service_name
        run: |
          docker exec -it your_service_name pnpm run test

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yaml down
