name: NestJs CI

on:
  push:
    branches:
      - master
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: '../../docker-compose.yml'
          test-container: 'reservations-service'
